[package]
name = "mot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.0"
rosc = "0.9.1"
clap = "4.1.4"
rand = "0.8.5"
once_cell = "1.17.0"