on: [push]

name: mot build

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: sudo apt-get install libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
