name: mot build and test
on: [push, pull_request]

jobs:
  test:
    name: cargo test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y libasound2-dev pkg-config
      - run: cargo test
      - run: cargo build --release
